#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}Trying to build global.${NC}"

start_build=$(date +%s%3N)
if make; then
    end_build=$(date +%s%3N)
    build_time=$((end_build - start_build))
    echo -e "${GREEN}Build global successful in ${build_time} milliseconds.${NC}"
    
else
    end_build=$(date +%s%3N)
    build_time=$((end_build - start_build))
    echo -e "${RED}Build global failed in ${build_time} milliseconds.${NC}"
fi
